/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFoundation,
  IFoundationInterface,
} from "../../../contracts/donate.sol/IFoundation";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "sendHelp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_description",
        type: "string",
      },
    ],
    name: "updateFoundationDescription",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFoundation__factory {
  static readonly abi = _abi;
  static createInterface(): IFoundationInterface {
    return new utils.Interface(_abi) as IFoundationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFoundation {
    return new Contract(address, _abi, signerOrProvider) as IFoundation;
  }
}
