/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Foundation } from "./Foundation";
export type { FundManager } from "./FundManager";
export type { IFoundation } from "./IFoundation";
