/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mytokenSol from "./mytoken.sol";
export type { mytokenSol };
export * as factories from "./factories";
export type { IERC20 } from "./interfaces/IERC20";
export { IERC20__factory } from "./factories/interfaces/IERC20__factory";
export type { ERC20Token } from "./mytoken.sol/ERC20Token";
export { ERC20Token__factory } from "./factories/mytoken.sol/ERC20Token__factory";
