/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { Foundation } from "./contracts/donate.sol/Foundation";
export { Foundation__factory } from "./factories/contracts/donate.sol/Foundation__factory";
export type { FundManager } from "./contracts/donate.sol/FundManager";
export { FundManager__factory } from "./factories/contracts/donate.sol/FundManager__factory";
export type { IFoundation } from "./contracts/donate.sol/IFoundation";
export { IFoundation__factory } from "./factories/contracts/donate.sol/IFoundation__factory";
