/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as donateSol from "./donate.sol";
export * as interfaces from "./interfaces";
export * as mytokenSol from "./mytoken.sol";
